##########################

LIBNAME := vector

BASEDIR := ..

SRCS := vector.bas

HDRS := $(wildcard *.bi)
HDRS += $(wildcard ../inc/*.bi)

DEP_LIBS :=

include ../library.inc

.PHONY : clean
clean: clean_library
